"use client";
import { useEffect, useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Copy, PartyPopper, X } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Card, CardContent } from '@/components/ui/card';
import { bidScenarios, futureActions, gameByNodeId, repairOptions, repairScenarios, selectedKnowMeQuestions, softOptions, tokenCategories, type GameDefinition, type GameResult, type RelationshipSignals } from '@/lib/game/games';
import { connectionSignal, scoreGame } from '@/lib/game/game-scoring';
import { cn } from '@/lib/utils';
import type { PathNode } from '@/types/domain';

type Props={open:boolean; node:PathNode|null; partnerName:string; completed:boolean; signals:RelationshipSignals; allResults:Record<string,GameResult>; onOpenChange:(o:boolean)=>void; onComplete:(result:GameResult)=>void; onReset:()=>void; onReplay:(nodeId:string)=>void};
type Phase='play'|'handoff'|'reveal'|'result'|'snapshot';
const emptyTokens=()=>Object.fromEntries(tokenCategories.map(c=>[c,0]));
export function RelationshipGameModal({open,node,partnerName,completed,signals,allResults,onOpenChange,onComplete,onReset,onReplay}:Props){
 const game=node?gameByNodeId[node.id]:undefined; const [step,setStep]=useState(0); const [phase,setPhase]=useState<Phase>('play'); const [answers,setAnswers]=useState<Record<string,any>>({}); const [result,setResult]=useState<GameResult|null>(null); const partner=partnerName||'Partner';
 useEffect(()=>{ if(open){ queueMicrotask(()=>{setStep(0);setPhase('play');setAnswers({youTokens:emptyTokens(),partnerTokens:emptyTokens()});setResult(null);});} },[open,node?.id]);
 const total=useMemo(()=>game?stepsFor(game).length:1,[game]); const current=game?stepsFor(game)[step]:null; if(!node||!game) return null;
 const finish=(extra:Record<string,any>={})=>{const merged={...answers,...extra}; const r=scoreGame(game,merged,completed); setAnswers(merged); setResult(r); setPhase('result'); onComplete(r);};
 const canContinue=validate(game,step,answers);
 const go=()=>{ if(game.id==='pulse-check'&&step===3){setPhase('handoff');return;} if(game.id==='pulse-check'&&step===7){finish();return;} if(game.id==='know-me-now'&&step===2){setPhase('handoff');return;} if(game.id==='know-me-now'&&step===5){setPhase('reveal');return;} if(game.id==='bid-catcher'&&step===9){finish();return;} if(game.id==='repair-lab'&&step===6){finish();return;} if(game.id==='appreciation-drop'&&step===2){setPhase('handoff');return;} if(game.id==='appreciation-drop'&&step===3){finish();return;} if(game.id==='future-draft'&&step===0){setPhase('handoff');return;} if(game.id==='future-draft'&&step===2){finish();return;} setStep(s=>s+1); };
 const content=()=>{
  if(phase==='handoff') return <Handoff partner={handoffName(game,step,partner)} onContinue={()=>{setPhase('play');setStep(s=>s+1)}}/>;
  if(phase==='reveal') return <Reveal game={game} answers={answers} onContinue={()=>finish()}/>;
  if(phase==='result'&&result) return <Result result={result} onClose={()=>onOpenChange(false)} onSnapshot={()=>setPhase('snapshot')}/>;
  if(phase==='snapshot') return <Snapshot signals={signals} results={allResults} onReset={onReset} onReturn={()=>onOpenChange(false)} onReplay={onReplay}/>;
  return <Step game={game} index={step} answers={answers} setAnswers={setAnswers} partner={partner}/>;
 };
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex max-h-[96vh] flex-col overflow-hidden rounded-3xl p-0 sm:max-w-2xl max-sm:h-[96vh]"><div className="bg-gradient-to-r from-[#ff5b7f] via-[#ff6b6b] to-[#ff8a5b] p-5 text-white"><DialogHeader><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.18em] text-white/80">{game.estimatedTime} • {phase==='play'?`Step ${step+1} of ${total}`:'Result'}</p><DialogTitle className="text-2xl font-black">{phase==='snapshot'?'Your Relationship Snapshot':game.title}</DialogTitle><p className="mt-1 text-sm text-white/90">{game.description}</p></div><button onClick={()=>onOpenChange(false)} className="rounded-full bg-white/20 p-2"><X className="size-4"/></button></div><Progress value={phase==='result'||phase==='snapshot'?100:((step+1)/total)*100} className="mt-4 h-2 bg-white/30 [&>div]:bg-white"/></DialogHeader></div><div className="flex-1 overflow-y-auto p-5"><AnimatePresence mode="wait"><motion.div key={`${phase}-${step}`} initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-12}} className="space-y-4">{content()}</motion.div></AnimatePresence></div>{phase==='play'&&<div className="flex items-center justify-between border-t bg-white p-4"><Button variant="outline" onClick={()=>onOpenChange(false)}>Close</Button><div className="text-sm text-rose-600">{!canContinue?'Answer required':''}</div><Button disabled={!canContinue} onClick={go} className="min-h-11 bg-rose-500 hover:bg-rose-600">Continue</Button></div>}</DialogContent></Dialog>;
}
function stepsFor(g:GameDefinition){ if(g.id==='pulse-check')return Array(8).fill(0); if(g.id==='know-me-now')return Array(6).fill(0); if(g.id==='bid-catcher')return Array(10).fill(0); if(g.id==='repair-lab')return Array(7).fill(0); if(g.id==='appreciation-drop')return Array(4).fill(0); return Array(3).fill(0); }
function handoffName(_g:GameDefinition,_step:number,p:string){ return p; }
function Choice({title,options,value,onPick}:{title:string;options:string[];value?:string;onPick:(v:string)=>void}){return <div><h3 className="font-bold text-zinc-900">{title}</h3><div className="mt-3 grid gap-2 sm:grid-cols-2">{options.map(o=><button key={o} onClick={()=>onPick(o)} className={cn('min-h-12 rounded-2xl border p-3 text-left text-sm font-semibold transition',value===o?'border-rose-500 bg-rose-50 text-rose-700 shadow-sm':'border-zinc-200 bg-white hover:border-rose-200')}>{o}</button>)}</div></div>}
function Scale({title,value,onPick,labels}:{title:string;value?:number;onPick:(v:number)=>void;labels:string[]}){return <div><h3 className="font-bold">{title}</h3><div className="mt-3 flex gap-2">{[1,2,3,4,5].map(n=><button key={n} onClick={()=>onPick(n)} className={cn('grid size-12 place-items-center rounded-full border font-black',value===n?'border-rose-500 bg-rose-500 text-white':'border-zinc-200')}>{n}</button>)}</div><p className="mt-2 text-xs text-zinc-500">1 = {labels[0]} • 5 = {labels[1]}</p></div>}
function Step({game,index,answers,setAnswers,partner}:{game:GameDefinition;index:number;answers:Record<string,any>;setAnswers:(f:any)=>void;partner:string}){ const set=(k:string,v:any)=>setAnswers((a:Record<string,any>)=>({...a,[k]:v})); const title=index<4?'Your turn':`${partner}’s turn`;
 if(game.id==='pulse-check'){ const p=index<4?'you':'partner'; const qs=['feeling','energy','connected','need']; const q=qs[index%4]; return <><p className="rounded-full bg-rose-50 px-3 py-1 text-sm font-bold text-rose-600">{title}</p>{q==='feeling'?<Choice title="How are you feeling right now?" options={['Calm','Happy','Hopeful','Playful','Tired','Stressed','Disconnected','Overwhelmed']} value={answers[p]?.feeling} onPick={v=>set(p,{...answers[p],feeling:v})}/>:q==='energy'?<Scale title="How much emotional energy do you have?" labels={['Empty','Full']} value={answers[p]?.energy} onPick={v=>set(p,{...answers[p],energy:v})}/>:q==='connected'?<Scale title="How connected do you feel to your partner today?" labels={['Distant','Very connected']} value={answers[p]?.connected} onPick={v=>set(p,{...answers[p],connected:v})}/>:<Choice title="What would help you most today?" options={['Listen to me','Give me affection','Help me solve something','Give me space','Let’s do something fun','Reassure me']} value={answers[p]?.need} onPick={v=>set(p,{...answers[p],need:v})}/>}</>}
 if(game.id==='know-me-now'){const predict=index>=3; const q=selectedKnowMeQuestions[index%3]; return <><p className="rounded-full bg-rose-50 px-3 py-1 text-sm font-bold text-rose-600">{predict?`Predict ${partner}`:'Your private answers'}</p><Choice title={q.prompt} options={q.options} value={(predict?answers.guess:answers.actual)?.[q.id]} onPick={v=>set(predict?'guess':'actual',{...(predict?answers.guess:answers.actual),[q.id]:v})}/></>}
 if(game.id==='bid-catcher'){ const s=bidScenarios[Math.floor(index/2)]; return <><Card><CardContent className="p-4"><p className="text-sm text-zinc-500">Partner says</p><p className="text-lg font-black">“{s.line}”</p></CardContent></Card>{index%2===0?<Choice title="What is the hidden emotional bid?" options={s.bidOptions} value={answers[`${s.id}_bid`]} onPick={v=>set(`${s.id}_bid`,v)}/>:<Choice title="What is the most responsive answer?" options={s.responseOptions} value={answers[`${s.id}_response`]} onPick={v=>set(`${s.id}_response`,v)}/>}</>}
 if(game.id==='repair-lab'){ if(index===6) return <Choice title="What could you honestly take responsibility for?" options={['My tone','My timing','Interrupting','Making assumptions','Not listening carefully','I need more time before answering']} value={answers.ownership} onPick={v=>set('ownership',v)}/>; const s=repairScenarios[Math.floor(index/2)]; return <><Card><CardContent className="p-4"><p className="text-sm text-zinc-500">Harsh statement</p><p className="text-lg font-black">“{s.harsh}”</p></CardContent></Card>{index%2===0?<Choice title="Select the strongest soft-start replacement." options={softOptions} value={answers[`${s.id}_soft`]} onPick={v=>set(`${s.id}_soft`,v)}/>:<Choice title="Select the strongest repair response." options={repairOptions} value={answers[`${s.id}_repair`]} onPick={v=>set(`${s.id}_repair`,v)}/>}</>}
 if(game.id==='appreciation-drop'){ if(index===0)return <Choice title="Choose a trait." options={['Kindness','Patience','Humour','Reliability','Courage','Care','Effort','Thoughtfulness']} value={answers.trait} onPick={v=>set('trait',v)}/>; if(index===1)return <div><h3 className="font-bold">Complete: When you…</h3><input maxLength={100} className="mt-3 w-full rounded-2xl border p-3" value={answers.action||''} onChange={e=>set('action',e.target.value)} placeholder="made coffee before my early meeting"/><p className="mt-1 text-xs text-zinc-500">{(answers.action||'').length}/100</p></div>; if(index===2)return <Choice title="Choose the impact." options={['It made me feel supported','It made me feel calmer','It made me feel noticed','It reminded me we are a team','It made me feel loved','Custom impact']} value={answers.impact} onPick={v=>set('impact',v)}/>; return <><Card className="border-rose-200 bg-rose-50"><CardContent className="p-4 text-lg font-black">I appreciated your {(answers.trait||'care').toLowerCase()} when you {answers.action}. {answers.impact}.</CardContent></Card><Choice title={`${partner}, how did that land?`} options={['I felt deeply seen','I felt appreciated','It was nice but too general','Let’s talk about it']} value={answers.reaction} onPick={v=>set('reaction',v)}/></>}
 const p=index===0?'you':'partner'; if(index<2)return <TokenAllocation title={p==='you'?'Your private priority draft':`${partner}’s private priority draft`} tokens={answers[`${p}Tokens`]||emptyTokens()} onChange={v=>set(`${p}Tokens`,v)}/>; return <><Comparison a={answers.youTokens||emptyTokens()} b={answers.partnerTokens||emptyTokens()} partner={partner}/><Choice title="Choose one shared action." options={futureActions} value={answers.sharedAction} onPick={v=>set('sharedAction',v)}/></> }
function TokenAllocation({title,tokens,onChange}:{title:string;tokens:Record<string,number>;onChange:(v:Record<string,number>)=>void}){const total=Object.values(tokens).reduce((a,b)=>a+b,0); return <div><h3 className="font-bold">{title}</h3><p className={cn('mt-1 text-sm',total===5?'text-emerald-600':'text-zinc-500')}>{total}/5 tokens allocated. Exactly five required.</p><div className="mt-3 space-y-2">{tokenCategories.map(c=><div key={c} className="flex items-center justify-between rounded-2xl border p-3"><span className="font-semibold">{c}</span><div className="flex items-center gap-3"><Button size="sm" variant="outline" onClick={()=>onChange({...tokens,[c]:Math.max(0,(tokens[c]||0)-1)})}>−</Button><span className="w-5 text-center font-black">{tokens[c]||0}</span><Button size="sm" variant="outline" disabled={total>=5} onClick={()=>onChange({...tokens,[c]:(tokens[c]||0)+1})}>+</Button></div></div>)}</div></div>}
function Comparison({a,b,partner}:{a:Record<string,number>;b:Record<string,number>;partner:string}){return <div className="space-y-2">{tokenCategories.map(c=><div key={c} className="grid grid-cols-[1fr_auto_auto] gap-3 rounded-xl bg-zinc-50 p-2 text-sm"><span>{c}</span><b>You: {a[c]||0}</b><b>{partner}: {b[c]||0}</b></div>)}</div>}
function Handoff({partner,onContinue}:{partner:string;onContinue:()=>void}){return <div className="grid min-h-[360px] place-items-center text-center"><div><h3 className="text-3xl font-black">Answer saved.</h3><p className="mt-3 text-zinc-600">Pass the phone to {partner}. Private answers stay hidden until reveal.</p><Button className="mt-6 min-h-12 bg-rose-500" onClick={onContinue}>I’m {partner} — continue</Button></div></div>}
function Reveal({game,answers,onContinue}:{game:GameDefinition;answers:Record<string,any>;onContinue:()=>void}){return <div><h3 className="text-2xl font-black">Reveal</h3>{selectedKnowMeQuestions.map(q=><div key={q.id} className="mt-3 rounded-2xl bg-zinc-50 p-3"><p className="font-bold">{q.prompt}</p><p>You chose: {answers.actual?.[q.id]}</p><p>Prediction: {answers.guess?.[q.id]}</p></div>)}<Button className="mt-5 bg-rose-500" onClick={onContinue}>See results</Button></div>}
function Result({result,onClose,onSnapshot}:{result:GameResult;onClose:()=>void;onSnapshot:()=>void}){return <div className="text-center"><PartyPopper className="mx-auto size-12 text-rose-500"/><h3 className="mt-2 text-2xl font-black">{result.headline}</h3><p className="mt-2 text-zinc-600">{result.insight}</p><div className="my-4 rounded-2xl bg-rose-50 p-4 text-left">{result.details.map(d=><p key={d} className="text-sm font-semibold text-zinc-700">• {d}</p>)}</div><p className="font-black text-rose-600">XP earned: {result.xpEarned}</p>{result.details[0]?.startsWith('I appreciated')&&<Button variant="outline" className="mt-3" onClick={()=>navigator.clipboard?.writeText(result.details[0])}><Copy className="mr-2 size-4"/>Copy card</Button>}<div className="mt-5 flex flex-wrap justify-center gap-2"><Button onClick={onClose} className="bg-rose-500">Continue journey</Button><Button variant="outline" onClick={onSnapshot}>Relationship Snapshot</Button></div></div>}
function Snapshot({signals,results,onReset,onReturn,onReplay}:{signals:RelationshipSignals;results:Record<string,GameResult>;onReset:()=>void;onReturn:()=>void;onReplay:(nodeId:string)=>void}){const signal=connectionSignal(signals); const entries=Object.entries(signals).filter(([,v])=>typeof v==='number') as [string,number][]; const strong=entries.sort((a,b)=>b[1]-a[1])[0]?.[0]||'appreciation'; const action=Object.values(results).reverse().find(r=>r.suggestedAction)?.suggestedAction||'Take a 10-minute phone-free walk'; return <div><h3 className="text-2xl font-black">Connection Signal: {signal}%</h3><p className="mt-2 rounded-2xl bg-amber-50 p-3 text-sm text-amber-800">Emome provides relationship reflection and conversation tools, not a clinical diagnosis.</p><div className="mt-4 grid gap-2">{['attunement','responsiveness','repair','appreciation','alignment','consistency'].map(k=><div key={k} className="flex justify-between rounded-xl bg-zinc-50 p-3 capitalize"><span>{k}</span><b>{signals[k as keyof RelationshipSignals]??'—'}</b></div>)}</div><Card className="mt-4"><CardContent className="space-y-3 p-4"><p><b>Strongest connection signal:</b> You currently show your strongest connection through {strong}.</p><p><b>Most useful growth opportunity:</b> You may benefit from checking what support your partner wants before offering solutions.</p><p><b>One action for today:</b> {action}</p></CardContent></Card><div className="mt-4 flex flex-wrap gap-2"><Button variant="outline" onClick={()=>onReplay('foundations-u1-daily-checkin')}>Replay a game</Button><Button variant="outline" onClick={onReset}>Reset demo</Button><Button className="bg-rose-500" onClick={onReturn}>Return to journey</Button></div></div>}
function validate(g:GameDefinition,i:number,a:Record<string,any>){ if(g.id==='pulse-check'){const p=i<4?'you':'partner',q=['feeling','energy','connected','need'][i%4]; return Boolean(a[p]?.[q]);} if(g.id==='know-me-now'){const q=selectedKnowMeQuestions[i%3].id; return Boolean((i>=3?a.guess:a.actual)?.[q]);} if(g.id==='bid-catcher'){const s=bidScenarios[Math.floor(i/2)]; return Boolean(a[`${s.id}_${i%2===0?'bid':'response'}`]);} if(g.id==='repair-lab'){if(i===6)return Boolean(a.ownership); const s=repairScenarios[Math.floor(i/2)]; return Boolean(a[`${s.id}_${i%2===0?'soft':'repair'}`]);} if(g.id==='appreciation-drop'){return i===0?Boolean(a.trait):i===1?Boolean(a.action?.trim()):i===2?Boolean(a.impact):Boolean(a.reaction);} if(g.id==='future-draft'){ if(i===2)return Boolean(a.sharedAction); const t=i===0?a.youTokens:a.partnerTokens; return Object.values(t||{}).reduce((x:any,y:any)=>x+y,0)===5;} return true;}
